#!/QOpenSys/pkgs/bin/bash

# Path to .env file (adjust if needed)
ENV_FILE=".env"
OUTPUT_HEADER="include/redis_config.h"

# Check if .env exists
if [ ! -f "$ENV_FILE" ]; then
    echo "Error: .env file not found in $(pwd)"
    exit 1
fi

# Create or overwrite the header file
cat > "$OUTPUT_HEADER" << 'EOF'
/* Generated by generate_config.sh - DO NOT EDIT MANUALLY */
#ifndef REDIS_CONFIG_H
#define REDIS_CONFIG_H

EOF

# Read .env and generate #define directives
while IFS='=' read -r key value; do
    # Skip empty, comment lines, and build-only flags
    [[ -z "$key" || "$key" =~ ^# ]] && continue
    [[ "$key" == "USE_ICONV" ]] && continue
    # Trim whitespace
    key=$(echo "$key" | xargs)
    value=$(echo "$value" | xargs)
    # Convert to uppercase and replace invalid characters for C #define
    define_key=$(echo "$key" | tr '[:lower:]' '[:upper:]' | tr -d '-')
    echo "#define $define_key \"$value\"" >> "$OUTPUT_HEADER"
done < "$ENV_FILE"

echo "#endif /* REDIS_CONFIG_H */" >> "$OUTPUT_HEADER"

# Copy headers to srcfile/ for ILE C compiler (INCDIR doesn't work reliably
# with quoted includes on IBM i - compiler finds headers in source dir)
cp "$OUTPUT_HEADER" srcfile/redis_config.h
cp include/redis_utils.h srcfile/redis_utils.h

echo "Generated $OUTPUT_HEADER from $ENV_FILE"
